name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.NODE_CLI }}

      - name: Checkout Repository
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Publish Packages
        if: ${{ steps.release.outputs.releases_created }}
        run: npx lerna publish from-package --no-push --no-private --yes --loglevel debug
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
